package com.lifelover.companion159.domain.usecases

import android.util.Log
import com.lifelover.companion159.data.remote.sync.SyncQueueManager
import com.lifelover.companion159.data.repository.InventoryRepository
import com.lifelover.companion159.domain.models.AppError
import com.lifelover.companion159.domain.models.DisplayCategory
import com.lifelover.companion159.domain.models.InventoryItem
import com.lifelover.companion159.domain.models.toStorageCategory
import com.lifelover.companion159.domain.validation.InputValidator
import javax.inject.Inject

/**
 * Use case for adding new inventory item
 *
 * Business rules:
 * - Name cannot be empty and must be 1-100 characters
 * - Quantities must be non-negative (0-999999)
 * - Display category determines storage category
 * - Item automatically queued for sync after creation
 *
 * Responsibilities:
 * - Validate all input fields
 * - Map display category to storage category
 * - Create domain model
 * - Delegate to repository for persistence
 * - Enqueue item for sync to server
 *
 * @param repository Inventory repository for data persistence
 * @param syncQueueManager Sync queue manager for server synchronization
 */
class AddItemUseCase @Inject constructor(
    private val repository: InventoryRepository,
    private val syncQueueManager: SyncQueueManager
) {
    companion object {
        private const val TAG = "AddItemUseCase"
    }

    suspend operator fun invoke(
        name: String,
        availableQuantity: Int,
        neededQuantity: Int,
        displayCategory: DisplayCategory
    ): Result<Unit> {
        return try {
            Log.d(TAG, "=== ADD ITEM USE CASE ===")
            Log.d(TAG, "Input: name='$name', available=$availableQuantity, needed=$neededQuantity, category=${displayCategory.name}")

            // Step 1: Validate input
            val validationResult = InputValidator.validateNewItem(
                name = name,
                availableQuantity = availableQuantity,
                neededQuantity = neededQuantity
            )

            validationResult.fold(
                onSuccess = { validated ->
                    Log.d(TAG, "✅ Validation passed")
                    Log.d(TAG, "Validated: name='${validated.name}', available=${validated.availableQuantity}, needed=${validated.neededQuantity}")

                    // Step 2: Map display category to storage category
                    val storageCategory = displayCategory.toStorageCategory()
                    Log.d(TAG, "Mapped: ${displayCategory.name} → ${storageCategory.name}")

                    // Step 3: Create domain model
                    val item = InventoryItem(
                        id = 0, // Auto-generated by Room
                        itemName = validated.name,
                        availableQuantity = validated.availableQuantity,
                        neededQuantity = validated.neededQuantity,
                        category = storageCategory,
                        crewName = "" // Will be set by repository based on current position
                    )

                    // Step 4: Save to repository (pure data operation)
                    Log.d(TAG, "Saving to repository...")
                    val insertedId = repository.insertItem(item)
                    Log.d(TAG, "✅ Item inserted with ID: $insertedId")

                    // Step 5: Enqueue for sync (business logic)
                    Log.d(TAG, "Enqueueing for sync...")
                    syncQueueManager.enqueueInsert(localItemId = insertedId)
                    Log.d(TAG, "✅ Item enqueued for sync")

                    Log.d(TAG, "✅ Add item completed successfully")
                    Log.d(TAG, "=========================")
                    Result.success(Unit)
                },
                onFailure = { error ->
                    Log.w(TAG, "⚠️ Validation failed: ${error.message}")
                    Log.d(TAG, "=========================")
                    Result.failure(error)
                }
            )

        } catch (e: Exception) {
            Log.e(TAG, "❌ Failed to add item", e)
            Log.d(TAG, "=========================")
            Result.failure(
                if (e is AppError) e
                else AppError.Unknown("Failed to add item: ${e.message}", e)
            )
        }
    }
}