package com.lifelover.companion159.data.remote.sync

import com.lifelover.companion159.data.local.entities.InventoryItemEntity
import com.lifelover.companion159.data.remote.dto.SupabaseInventoryItemDto
import com.lifelover.companion159.domain.models.StorageCategory
import java.text.SimpleDateFormat
import java.util.*

/**
 * Mapper between Room entities and Supabase DTOs
 *
 * Handles:
 * - Category mapping (AMMUNITION → "БК", EQUIPMENT → "Обладнання")
 * - Timestamp conversion (Date ↔ ISO 8601 String)
 * - Default values for Supabase-specific fields
 */
object SyncMapper {

    private val iso8601Format = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX", Locale.US).apply {
        timeZone = TimeZone.getTimeZone("UTC")
    }

    /**
     * Convert Room Entity to Supabase DTO
     * Used for uploading local data to server
     */
    fun entityToDto(entity: InventoryItemEntity): SupabaseInventoryItemDto {
        return SupabaseInventoryItemDto(
            id = entity.supabaseId, // null for new items
            tenantId = 0, // Always 0 per requirements
            crewName = entity.crewName,
            itemName = entity.itemName,
            availableQuantity = entity.availableQuantity,
            neededQuantity = entity.neededQuantity,
            itemCategory = mapCategoryToSupabase(entity.category),
            unit = "шт.", // Fixed value
            priority = entity.priority,
            crewType = null, // Empty per requirements
            description = null,
            notes = null,
            lastNeedUpdatedAt = null,
            neededBy = null,
            createdBy = null,
            updatedBy = null,
            metadata = null,
            isActive = entity.isActive,
            createdAt = formatDate(entity.createdAt),
            updatedAt = formatDate(entity.lastModified)
        )
    }

    /**
     * Convert Supabase DTO to Room Entity
     * Used for downloading server data to local DB
     *
     * @param dto Supabase DTO
     * @param userId Current user ID (nullable as per requirements)
     * @param markAsSynced Whether to set needsSync = false
     */
    fun dtoToEntity(
        dto: SupabaseInventoryItemDto,
        userId: String?,
        markAsSynced: Boolean = true
    ): InventoryItemEntity {
        return InventoryItemEntity(
            id = 0, // Will be auto-generated by Room
            supabaseId = dto.id,
            userId = userId,
            crewName = dto.crewName,
            itemName = dto.itemName,
            availableQuantity = dto.availableQuantity,
            neededQuantity = dto.neededQuantity,
            category = mapCategoryFromSupabase(dto.itemCategory),
            priority = dto.priority,
            isActive = dto.isActive,
            createdAt = parseDate(dto.createdAt) ?: Date(),
            lastModified = parseDate(dto.updatedAt) ?: Date(),
            lastSynced = if (markAsSynced) Date() else null,
            needsSync = !markAsSynced
        )
    }

    /**
     * Update existing Room entity with Supabase DTO data
     * Preserves local ID while updating fields
     *
     * Used during conflict resolution (last write wins)
     */
    fun updateEntityFromDto(
        existingEntity: InventoryItemEntity,
        dto: SupabaseInventoryItemDto
    ): InventoryItemEntity {
        return existingEntity.copy(
            supabaseId = dto.id,
            itemName = dto.itemName,
            availableQuantity = dto.availableQuantity,
            neededQuantity = dto.neededQuantity,
            category = mapCategoryFromSupabase(dto.itemCategory),
            priority = dto.priority,
            isActive = dto.isActive,
            lastModified = parseDate(dto.updatedAt) ?: Date(),
            lastSynced = Date(),
            needsSync = false
        )
    }

    /**
     * Map StorageCategory enum to Supabase item_category string
     *
     * AMMUNITION → "БК"
     * EQUIPMENT → "Обладнання"
     */
    private fun mapCategoryToSupabase(category: StorageCategory): String {
        return when (category) {
            StorageCategory.AMMUNITION -> "БК"
            StorageCategory.EQUIPMENT -> "Обладнання"
        }
    }

    /**
     * Map Supabase item_category string to StorageCategory enum
     *
     * "БК" → AMMUNITION
     * "Обладнання" → EQUIPMENT
     * null or unknown → EQUIPMENT (default)
     */
    private fun mapCategoryFromSupabase(category: String?): StorageCategory {
        return when (category?.trim()) {
            "БК" -> StorageCategory.AMMUNITION
            "Обладнання" -> StorageCategory.EQUIPMENT
            else -> StorageCategory.EQUIPMENT // Default fallback
        }
    }

    /**
     * Format Date to ISO 8601 string for Supabase
     * Example: "2025-10-14T10:30:00.000Z"
     */
    private fun formatDate(date: Date?): String? {
        return date?.let { iso8601Format.format(it) }
    }

    /**
     * Parse ISO 8601 string from Supabase to Date
     * Returns null if parsing fails
     */
    private fun parseDate(dateString: String?): Date? {
        return try {
            dateString?.let { iso8601Format.parse(it) }
        } catch (e: Exception) {
            null
        }
    }
}